.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH orayta 1 "September 28, 2013" "" "Orayta - jewish books"

.SH NAME
orayta \- Jewish books program

.SH SYNOPSIS
.B orayta
.IP "orayta -v"
.IP "orayta -D booktext"
.br

.SH DESCRIPTION
.B orayta 
is a cross-platform Jewish books program.
.PP

.SH OPTIONS
.IP "-D booktext.txt, --buildDB booktext.txt" 
Tells orayta to builds a search ".DB" and ".LMP" files for the given book's text, and quit.
.IP "-v, --version"
Prints orayta's version and quits.


.SH SEE ALSO
https://code.google.com/p/orayta/wiki/HebrewFAQ

.SH AUTHOR
Moshe Wagner (moshe.wagner@gmail.com)

