Document: orayta
Title: Debian orayta Manual
Author: <insert document author here>
Abstract: This manual describes what orayta is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orayta/orayta.sgml.gz

Format: postscript
Files: /usr/share/doc/orayta/orayta.ps.gz

Format: text
Files: /usr/share/doc/orayta/orayta.text.gz

Format: HTML
Index: /usr/share/doc/orayta/html/index.html
Files: /usr/share/doc/orayta/html/*.html
